# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2924dbe6faa94b1219557a2f09cd27d1ba1f0febf2e833e14fedea33f3b551f78f6760ceb8c9d0d717909137989ade352a6e28ecd76596631eb755cc4b4e072a

test:
  secret_key_base: 5aef54e23761574eae83e97c05bec14128586ce0e8924bd9fbfb0a7017ca2671132b5153f0b28c54cb490c13ad9270ae2d019a1e7b14ddbf5ab865be1135d2fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
